### ISSUE TITLE
Pension Administrator/Number, NHF Details not available on Employee Details Screen

### ISSUE THREAD

**Issue by jayekwueme** [Mandiklopper/UBA-People-Connect#109]
The Pension Administrator/Number, NHF Details not viewable on the employee details screen.

I also do not see a data capture field for the Prepaid Card PIN details.

**Comment by jayekwueme** [comment]
Closing this because it had been logged earlier by Robert

**Comment by jayekwueme** [comment]
Issue is with the data migrated for all staff. Robert's log is on users updating these fields on ESS

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=218 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Updated YEXITCLRES_RSPE on NGADEV will move to UBA with next patch
