### ISSUE TITLE
WF: Extended Sick Leave Notification

### ISSUE THREAD

**Issue by MartinKruger** [Mandiklopper/UBA-People-Connect#117]
[Senseable Ticket #212](https://senseable.co.za/scp/tickets.php?id=86)
- Email notification for extended sick leave to be reviewed one month to the expiration of the leave period.

**Comment by P1errevanZyl** [comment]
This workflow has been done on 10.16, and patched to DEV & TEST, as well as UBA TEST & UAT.

It has been added to the recurring task management on 10.16
